### ISSUE TITLE
Github Releases?

### ISSUE THREAD

**Issue by nileshpatra** [pyranges/pyrle#2]
Hi,
I need to use this in a project and it would be great if you could tag the releases here.

**Comment by nileshpatra** [comment]
@endrebak could you please do the needful?

**Comment by endrebak** [comment]
What exactly do you need me to do? :)

Is it to add a release here: https://github.com/pyranges/pyrle/releases

Whenever I update pyrle?

Just curious: what difference does it make? How/why do you use the releases?

**Comment by nileshpatra** [comment]
Hi @endrebak 
> What exactly do you need me to do? :)

> Is it to add a release here: https://github.com/pyranges/pyrle/release

Yes!

>Whenever I update pyrle?

And yes! But for now: can you please add in a release?
Maybe v1.0?

>Just curious: what difference does it make? How/why do you use the releases?

We want to ship this in Debian as a package and packages w/o any release tags are hard to maintain and not very recommend to package.
I want to package this, but this is a hurdle.

**Comment by endrebak** [comment]
Cool! I want to do this, I'll have it done by the end of next week. Same with pyranges and the NCLS :)

**Comment by endrebak** [comment]
Does having the version 1.0.0 have any advantage over 0.0.X?

**Comment by nileshpatra** [comment]
> Does having the version 1.0.0 have any advantage over 0.0.X?

Nah, it was just a suggestion. Use any scheme you'd like to, that works for me. But please just add-in the release tags :-)

**Comment by endrebak** [comment]
0.031 is now a tagged release  :)

**Comment by nileshpatra** [comment]
Many thanks! \o/
